version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    macos:
      xcode: "14.1.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Android Build
          # command: bundle exec fastlane $FASTLANE_LANE
          command: cd android && bundle exec fastlane dev
      - run:
          name: iOS Build
          # command: bundle exec fastlane $FASTLANE_LANE
          command: cd ios && bundle exec fastlane development
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
